export type Lang = 'en' | 'ar'
export type Label = { en: string; ar: string }

export const L = {
  roles: {
    coordinator: { en: 'Coordinator', ar: 'امين مرحلة' },
    servant:     { en: 'Servant',     ar: 'خادم' },
    student:     { en: 'Student',     ar: 'مخدوم' },
    students:    { en: 'Students',    ar: 'المخدومون' },
  },
  entities: {
    family:      { en: 'Family',      ar: 'اسرة' },
    class:       { en: 'Class',       ar: 'فصل' },
    grade:       { en: 'Grade',       ar: 'مرحلة' },
  },
  status: {
    pending:     { en: 'Pending',     ar: 'في الانتظار' },
    accepted:    { en: 'Accepted',    ar: 'مقبول' },
    rejected:    { en: 'Rejected',    ar: 'مرفوض' },
    transferred: { en: 'Transferred', ar: 'محوّل' },
    approved:    { en: 'Approved',    ar: 'مقبول' },
    all:         { en: 'All',         ar: 'الكل' },
  },
  nav: {
    home:        { en: 'Home',         ar: 'الرئيسية' },
    students:    { en: 'Students',     ar: 'المخدومون' },
    reading:     { en: 'Reading',      ar: 'القراءة' },
    history:     { en: 'History',      ar: 'السجل' },
    ranks:       { en: 'Ranks',        ar: 'الترتيب' },
    logout:      { en: 'Logout',       ar: 'خروج' },
    today:       { en: 'Today',        ar: 'اليوم' },
    me:          { en: 'Me',           ar: 'أنا' },
  },
  auth: {
    welcomeBack:       { en: 'Welcome back',              ar: 'أهلاً بك' },
    continueReading:   { en: 'Continue your daily reading', ar: 'تابع قراءتك اليومية' },
    email:             { en: 'Email',                     ar: 'البريد الإلكتروني' },
    password:          { en: 'Password',                  ar: 'كلمة المرور' },
    signIn:            { en: 'Sign In',                   ar: 'تسجيل الدخول' },
    signingIn:         { en: 'Signing in…',               ar: 'جاري الدخول…' },
    forgotPassword:    { en: 'Forgot password?',          ar: 'نسيت كلمة المرور؟' },
    signInWithGoogle:  { en: 'Sign in with Google',       ar: 'تسجيل الدخول بجوجل' },
    newHere:           { en: 'new here?',                 ar: 'جديد هنا؟' },
    imAStudent:        { en: "I'm a student",             ar: 'أنا مخدوم' },
    imATeacher:        { en: "I'm a teacher",             ar: 'أنا خادم' },
    signOut:           { en: 'Sign out',                  ar: 'تسجيل الخروج' },
    backToSignIn:      { en: 'Back to sign in',           ar: 'العودة لتسجيل الدخول' },
    resetPassword:     { en: 'Reset password',            ar: 'إعادة تعيين كلمة المرور' },
    resetSubtitle:     { en: "We'll send a reset link to your email", ar: 'سنرسل رابط إعادة التعيين لبريدك' },
    sendResetLink:     { en: 'Send Reset Link',           ar: 'إرسال الرابط' },
    sending:           { en: 'Sending…',                  ar: 'جاري الإرسال…' },
    checkInbox:        { en: 'Check your inbox',          ar: 'تحقق من بريدك' },
    resetLinkSent:     { en: 'A reset link has been sent to', ar: 'تم إرسال رابط إعادة التعيين إلى' },
    checkSpam:         { en: "Click the link in the email to set a new password. Check your spam folder if you don't see it.", ar: 'انقر الرابط في البريد لتعيين كلمة مرور جديدة. تحقق من مجلد الرسائل غير المرغوب فيها إن لم تجده.' },
    setNewPassword:    { en: 'Set new password',          ar: 'تعيين كلمة مرور جديدة' },
    chooseStrongPass:  { en: 'Choose a strong password',  ar: 'اختر كلمة مرور قوية' },
    newPassword:       { en: 'New Password',              ar: 'كلمة المرور الجديدة' },
    confirmPassword:   { en: 'Confirm Password',          ar: 'تأكيد كلمة المرور' },
    setNewPasswordBtn: { en: 'Set New Password',          ar: 'تعيين كلمة المرور' },
    updating:          { en: 'Updating…',                 ar: 'جاري التحديث…' },
    linkInvalid:       { en: 'Link invalid',              ar: 'الرابط غير صالح' },
    verifyingLink:     { en: 'Verifying reset link…',     ar: 'جاري التحقق من الرابط…' },
    passwordUpdated:   { en: 'Password updated! Redirecting to sign in…', ar: 'تم تحديث كلمة المرور! جاري التحويل…' },
  },
  register: {
    createAccount:     { en: 'Create account',            ar: 'إنشاء حساب' },
    joinSubtitle:      { en: 'Join Bible Kids',           ar: 'انضم لـ Bible Kids' },
    startClass:        { en: 'Start a class',             ar: 'ابدأ فصلاً' },
    teacherSubtitle:   { en: 'Register as a servant',     ar: 'سجّل كخادم' },
    verifyEmail:       { en: 'Verify your email',         ar: 'تحقق من بريدك' },
    enterOtp:          { en: 'Enter the code sent to',    ar: 'أدخل الرمز المرسل إلى' },
    otpPlaceholder:    { en: '8-digit code',              ar: 'رمز مكوّن من 8 أرقام' },
    verify:            { en: 'Verify',                    ar: 'تحقق' },
    verifying:         { en: 'Verifying…',                ar: 'جاري التحقق…' },
    resendOtp:         { en: 'Resend code',               ar: 'إعادة إرسال الرمز' },
    yourDetails:       { en: 'Your details',              ar: 'بياناتك' },
    fullName:          { en: 'Full name',                 ar: 'الاسم الكامل' },
    age:               { en: 'Age',                       ar: 'العمر' },
    gender:            { en: 'Gender',                    ar: 'الجنس' },
    male:              { en: 'Male',                      ar: 'ذكر' },
    female:            { en: 'Female',                    ar: 'أنثى' },
    selectFamily:      { en: 'Select family',             ar: 'اختر الأسرة' },
    selectGrade:       { en: 'Select grade',              ar: 'اختر المرحلة' },
    selectClass:       { en: 'Select class',              ar: 'اختر الفصل' },
    selectRole:        { en: 'Select role',               ar: 'اختر الدور' },
    register:          { en: 'Register',                  ar: 'تسجيل' },
    registering:       { en: 'Registering…',              ar: 'جاري التسجيل…' },
    sendCode:          { en: 'Send Code',                 ar: 'إرسال الرمز' },
    sending:           { en: 'Sending…',                  ar: 'جاري الإرسال…' },
    alreadyHaveAccount: { en: 'Already have an account?', ar: 'لديك حساب بالفعل؟' },
    signInHere:        { en: 'Sign in',                   ar: 'تسجيل الدخول' },
    emailVerified:     { en: 'Email verified',            ar: 'تم التحقق من البريد' },
    teacherBadge:      { en: 'Teacher account',           ar: 'حساب خادم' },
  },
  pending: {
    title:          { en: "You're in the queue",          ar: 'طلبك قيد المراجعة' },
    subtitle:       { en: "Your teacher will review your account. You'll be notified once approved — usually within 24 hours.", ar: 'سيراجع خادمك حسابك. ستُخطر بمجرد القبول — عادةً خلال 24 ساعة.' },
    waitingLabel:   { en: 'Waiting for teacher approval', ar: 'في انتظار موافقة الخادم' },
    inReview:       { en: 'In review',                    ar: 'قيد المراجعة' },
    startReading:   { en: "Start today's reading",        ar: 'ابدأ قراءة اليوم' },
    upNext:         { en: 'Up next',                      ar: 'التالي' },
  },
  admin: {
    overview:       { en: 'Overview',              ar: 'نظرة عامة' },
    totalUsers:     { en: 'Total Users',           ar: 'إجمالي المستخدمين' },
    totalStudents:  { en: 'Total Students',        ar: 'إجمالي المخدومين' },
    pendingApproval:{ en: 'Pending Approval',      ar: 'في انتظار الموافقة' },
    todayReading:   { en: "Today's Reading",       ar: 'قراءة اليوم' },
    noReadingToday: { en: 'No reading assigned for today', ar: 'لا توجد قراءة اليوم' },
    analytics:      { en: 'Analytics',             ar: 'الإحصائيات' },
    quickActions:   { en: 'Quick Actions',         ar: 'إجراءات سريعة' },
    manageStudents: { en: 'Manage Students',       ar: 'إدارة المخدومين' },
    assignReading:  { en: 'Assign Reading',        ar: 'تعيين القراءة' },
    readingRate:    { en: 'Reading Rate',          ar: 'معدل القراءة' },
    correctAnswers: { en: 'Correct Answers',       ar: 'الإجابات الصحيحة' },
    perClass:       { en: 'Per Class',             ar: 'لكل فصل' },
    management:     { en: 'Management',            ar: 'الإدارة' },
    searchByName:   { en: 'Search by name…',       ar: 'ابحث بالاسم…' },
    allTypes:       { en: 'All types',             ar: 'الكل' },
    coordinators:   { en: 'Coordinators',          ar: 'أمناء المراحل' },
    allClasses:     { en: 'All classes',           ar: 'كل الفصول' },
    noStudentsFound:{ en: 'No students found',     ar: 'لا يوجد مخدومون' },
    reject:         { en: 'Reject',                ar: 'رفض' },
    approve:        { en: 'Approve',               ar: 'قبول' },
    accept:         { en: 'Accept',                ar: 'قبول' },
    pending:        { en: 'pending',               ar: 'في الانتظار' },
    today:          { en: 'Today',                 ar: 'اليوم' },
    verses:         { en: 'verses',                ar: 'آيات' },
    kids:           { en: 'kids',                  ar: 'مخدومون' },
  },
  kid: {
    todayReading:    { en: "Today's Reading",      ar: 'قراءة اليوم' },
    peace:           { en: 'Peace,',               ar: 'السلام،' },
    noReadingToday:  { en: 'No Reading Today',     ar: 'لا توجد قراءة اليوم' },
    checkBackLater:  { en: 'Check back later for your next assignment.', ar: 'تحقق لاحقاً للقراءة القادمة.' },
    minRead:         { en: '~5 min read',          ar: '~٥ دقائق' },
    complete:        { en: 'Complete',             ar: 'مكتمل' },
    quickCheck:      { en: 'Quick check',          ar: 'اختبار سريع' },
    markComplete:    { en: 'Mark as Complete',     ar: 'تحديد كمكتمل' },
    marking:         { en: 'Marking…',             ar: 'جاري التحديث…' },
    readingComplete: { en: 'Reading Complete!',    ar: 'اكتملت القراءة!' },
    submitAnswers:   { en: 'Submit Answers',       ar: 'إرسال الإجابات' },
    submitting:      { en: 'Submitting…',          ar: 'جاري الإرسال…' },
    brilliantWork:   { en: 'Brilliant work!',      ar: 'عمل رائع!' },
    youEarned:       { en: 'You earned',           ar: 'حصلت على' },
    points:          { en: 'points!',              ar: 'نقطة!' },
    answerAll:       { en: 'Please answer all questions', ar: 'يرجى الإجابة على جميع الأسئلة' },
    // leaderboard
    classRanking:    { en: 'Class ranking',        ar: 'ترتيب الفصل' },
    leaderboard:     { en: 'Leaderboard',          ar: 'لوحة الترتيب' },
    noStudentsYet:   { en: 'No students yet',      ar: 'لا يوجد مخدومون بعد' },
    top10:           { en: 'Top 10!',              ar: 'أفضل ١٠!' },
    keepGoing:       { en: 'Keep going!',          ar: 'استمر!' },
    // history
    yourMonth:       { en: 'Your month',           ar: 'شهرك' },
    longestStreak:   { en: 'Longest streak',       ar: 'أطول سلسلة' },
    completion:      { en: 'Completion',           ar: 'الإتمام' },
    daysRead:        { en: 'Days read',            ar: 'أيام القراءة' },
    completed:       { en: 'Completed',            ar: 'مكتمل' },
    missed:          { en: 'Missed',               ar: 'فائت' },
    todayLabel:      { en: 'Today',                ar: 'اليوم' },
    // profile
    account:         { en: 'Account',              ar: 'الحساب' },
    profile:         { en: 'Profile',              ar: 'الملف الشخصي' },
    myClass:         { en: 'My class',             ar: 'فصلي' },
    totalPts:        { en: 'Total pts',            ar: 'إجمالي النقاط' },
    dayStreak:       { en: 'Day streak',           ar: 'سلسلة الأيام' },
    bestStreak:      { en: 'Best streak',          ar: 'أفضل سلسلة' },
    settings:        { en: 'Settings',             ar: 'الإعدادات' },
    dailyReminder:   { en: 'Daily reminder',       ar: 'تذكير يومي' },
    notifEnabled:    { en: 'Notifications enabled', ar: 'الإشعارات مفعّلة' },
    notifOff:        { en: 'Notifications off',    ar: 'الإشعارات متوقفة' },
    language:        { en: 'Language',             ar: 'اللغة' },
    english:         { en: 'English',              ar: 'English' },
    logOut:          { en: 'Log out',              ar: 'تسجيل الخروج' },
    signOutDevice:   { en: 'Sign out of this device', ar: 'تسجيل الخروج من هذا الجهاز' },
    profileNotFound: { en: 'Profile not found',   ar: 'الملف الشخصي غير موجود' },
  },
  common: {
    biblekids:  { en: 'Bible Kids', ar: 'Bible Kids' },
    loading:    { en: 'Loading…',   ar: 'جاري التحميل…' },
    error:      { en: 'Error',      ar: 'خطأ' },
    or:         { en: 'or',         ar: 'أو' },
  },
} as const
